#!/bin/bash

echo "=========================================="
echo "Manual GitHub Push Helper"
echo "=========================================="
echo ""
echo "Your repository is ready to push!"
echo "Location: $(pwd)"
echo ""
echo "To push manually, run these commands:"
echo ""
echo "1. Set your username:"
echo "   git config user.name \"tmiswrkspc\""
echo ""
echo "2. Set your email:"
echo "   git config user.email \"your-email@example.com\""
echo ""
echo "3. Push to GitHub:"
echo "   git push -u origin main"
echo ""
echo "When prompted for credentials:"
echo "   Username: tmiswrkspc"
echo "   Password: <paste your PAT>"
echo ""
echo "=========================================="
echo ""
echo "Alternative: Use GitHub CLI"
echo "   brew install gh"
echo "   gh auth login"
echo "   gh repo set-default tmiswrkspc/jobscraper"
echo "   git push -u origin main"
echo ""
echo "=========================================="
